[profile.default]
retries = 0
flaky-result = "fail"
leak-timeout = { period = "500ms", result = "fail" }
slow-timeout = { period = "30s", terminate-after = 3 }

[profile.ci]
fail-fast = false
retries = 0

[profile.ci.junit]
path = "junit.xml"
store-success-output = false
store-failure-output = true
